baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ANNIKOMPLISHMENTS'
theme = 'hugo-angus'
paginate = 8

[params]
  backgroundURL = ""
  logo = "TꕤDAY"
  isIconNav = true

[params.utteranc]
  enable = true
  repo = "Twor/blog-comment"
  issueTerm = "pathname"
  theme = "github-light"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# 主导航菜单
[menu]
  [[menu.main]]
    identifier = "posts"
    name="Posts"
    url="/"
    weight="1"
  [[menu.main]]
    identifier = "about"
    name="About"
    url="/about"
    weight="2"

